learning_users/basicapp/urls.py
from django.urls import path
from . import views

## template urls!

app_name = 'basicapp'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('user_login/',views.user_login, name = "user_login"),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('basicapp/', include('basicapp.urls')),
    path('logout/', views.user_logout, name = 'logout'),
    path('special/', views.special, name = 'special'), #page that can only be accessed if the user is logged in (not made)

]

learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete = models.CASCADE)

    #additional classes
    portfolio_site = models.URLField(blank = True) # blank = True allows user to leave this field blank without returning an error
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

    def __str__(self):
        return self.user.username

learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic','portfolio_site')

learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserProfileInfoForm, UserForm
from . import forms

#Login imports
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'basicapp/index.html')

@login_required #requires the user to be logged in to log them out
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in,  Nice!")

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = forms.UserForm(data = request.POST)
        profile_form = forms.UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password) # Sets the password as a Hash byb going into settings.py
            user.save() #Saved the hashed password to the database

            profile = profile_form.save(commit=False) #dont want to commit to the database yet otherwise may encounter collisions where the user will be overwritten
            profile.user = user # SETS UP ONE TO ONE RELATIONSHIP

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()


    return render(request, 'basicapp/registration.html',
                {'user_form':user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username') # gets username from login.html form
        password = request.POST.get('password') # gets password from login.html

        user = authenticate(username = username, password = password)

        if user: #if we have a user
            if user.is_active:
                login(request, user) #passes in the request, and the user that was just authenticated and logs that user in
                return HttpResponseRedirect(reverse('index')) #Redirects a successful logged in user to the view named index

            else:
                return HttpResponse("<h1>Account not Active</h1>")

        else:
            print("Someone Tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("<h1>Invalid Login details supplied</h1>")
    else:
        return render(request, 'basicapp/login.html', {})

learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark sticky-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="navbar-brand" href="{% url 'index' %}"> HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basicapp:register'%}">Register</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basicapp:user_login' %}">Login</a>
          </li>

          {% endif %}

        </ul>
      </div>

    </nav>

    <div class="container">
      {% block body %}
      {%endblock%}

    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

learning_users/templates/basicapp/index.html
{% extends "basicapp/base.html" %}
{% block body %}
<div class="jumbotron">
  <h1>DJANGO LEVEL 5</h1>
</div>

{% endblock %}

learning_users/templates/basicapp/login.html
{% extends "basicapp/base.html" %}
{% block body %}
  <div class="jumbotron">
    <h1>Please Log In</h1>
    <form action="{% url 'basicapp:user_login'%}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username"> <br>

      <label for="password"> Password: </label>
      <input type="password" name="password">

      <input type="submit" class="btn btn-success" value="Login">
    </form>
  </div>

{% endblock %}

learning_users/templates/basicapp/registration.html
{% extends "basicapp/base.html" %}
{% load staticfiles %}

{% block body %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering!</h1>
    {% else %}
      <h1>Register Here!</h1>
      <h1>Fill out the form</h1>

      <form enctype="multipart/form-data" method="post" > <!-- ALLOWS THE UPLOADING OF MULTIMEDIA DATA IMGS/VIDEOS ETC-->
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" class="btn btn-success" value="Register">
      </form>
    {% endif %}
  </div>
{% endblock %}